config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :events
  get '/home', to: 'events#index'

  resources :users, only: [:show]

  resources :events do 
    resources :attendances
  end 

  resources :charges

  resources :events do
    resources :event_pictures, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  after_create :attendance_send

  def attendance_send
    UserMailer.attendance_email(User.find(self.user_id), Event.find(self.event_id)).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :event_picture

  validates :start_date, 
    presence: true
    #impossible de créer un évent ou modif un évent du passé

  validates :duration, 
    presence: true
    #multiple de 5 et sup à 0

  validates :title, 
    presence: true, 
    length: { in: 5..140 }

  validates :description, 
    presence: true,
    length: { in: 20..1000 }

  validates :price, 
    presence: true,
    length: { in: 1..1000 }

  validates :location, 
    presence: true

  has_many :attendances
  has_many :users, through: :attendances
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances
  has_many :events, through: :attendances

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < EventsController
  def index 
    @attendances = Attendance.where(event_id: params[:event_id])
  end 
  
  def new
    @attendance = Attendance.new
    @event = Event.find(params[:event_id]) 
    @amount = @event.price 
  end
  
  def create
    @amount = Event.find(params[:event_id]).price * 100

    unless @amount == 0
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
        id: params[:stripeId],
      })
  
      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @amount,
        description: 'Rails Stripe customer',
        currency: 'eur',
      })

    Attendance.create(event_id: params[:event_id], user_id: current_user.id, stripe_customer_id: params[:stripeToken])

    else 
      Attendance.create(event_id: params[:event_id], user_id: current_user.id, stripe_customer_id: "azerty")
    end 

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/event_pictures_controller.rb
class EventPicturesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.event_picture.attach(params[:event_picture])
    redirect_to(event_path(@event))
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @administrator = User.find(@event.administrator_id)
    @attendants = Attendance.where(event_id: @event.id).count 
  end

  def new 
    @event = Event.new
    @user = current_user
  end 

  def create 
    @event = Event.new(post_params)
    @event.administrator_id = current_user.id
    if @event.save # essaie de sauvegarder en base @gossip
      Attendance.create(event_id: @event.id, user_id: current_user.id, stripe_customer_id: "azerty")
      redirect_to home_path
    else
      render :new
    end
  end 

  def edit
    @event = Event.find(params[:id]) 
  end 

  def update 
    @event = Event.find(params[:id])
    if @event.update(post_params)
      redirect_to event_path(@event.id)
    else
      render :edit
    end
  end 

  def destroy
    @event = Event.find(params[:id]) 
    @event.destroy 
    redirect_to events_path
  end 

  def post_params
    post_params = params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
  end 

  def correct_user
    unless current_user.id == Event.find(params[:id])[:administrator_id]
      flash[:danger] = "Vous ne pouvez pas réaliser cette action !"
      redirect_to events_path
    end 
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :correct_user, only: [:show]

  def show
    @current_user = current_user
    @events_admin = Event.where(administrator_id: current_user.id)
  end

  def correct_user
    unless current_user == User.find(params[:id])
      flash[:danger] = "Vous ne pouvez pas réaliser cette action !"
      redirect_to home_path
    end 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_pictures_helper.rb
module EventPicturesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/attendances/create.html.erb
<h2>Thanks, you paid <strong><%= @amount/100%></strong>!</h2>

app/views/attendances/index.html.erb
<div class="jumbotron">
  <div class="container">   
    <h1>Les participants de votre événement en détail</h1>
   	 <p><a class="btn btn-secondary btn-sm" href="<%= edit_event_path(params[:event_id])%>" role="button">Modifier l'événement »</a></p>
   	 <p><a href="<%= event_path(params[:event_id]) %>" class="btn btn-dark btn-sm" data-confirm="Etes-vous sûr de votre choix?" data-method="DELETE">Annuler l'événement »</a></p>
  </div>
</div>

<div class="container text-center">
  <div class="row">
	<% i = 0
	@attendances.each do |attendance| %>
	<div class="col-md-4 t-4 text-center">
	  <h4>Participant <%= i+1%> </h4>
	  <p>Email: <%=User.find(@attendances[i].user_id).email%></p>
	  <p>Prénom: <%=User.find(@attendances[i].user_id).first_name%></p>
	  <p>Nom: <%=User.find(@attendances[i].user_id).last_name%></p>
	</div>
	<% i += 1 
	end %>
  </div>

</div>

app/views/attendances/new.html.erb
<% if @amount ==0 %>
  <div class="row justify-content-center">
    <%= form_for [@event, @attendance] do |f| %>
      <div class="form-group text-right col-12">
        <button type="submit" class="btn btn-secondary">S'inscrire à cet évent</button>
      </div>
    <% end %>
  </div>

<% else %>
<%= form_tag event_attendances_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Montant: $<%= @amount%></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button w-100"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="New attendance"
          data-amount="<%= @amount *100%>"
          data-locale="auto"></script>
<% end %>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<div class="row justify-content-center">
    <%= form_for @event do |f| %>
      <div class="form-group col-12">
        <label>Titre de l'événement</label>
        <%= f.text_field :title, class: "form-control"%>
      </div>
      <div class="form-group col-12">
        <label>Description</label>
        <%= f.text_field :description, class: "form-control"%>
      </div>
      <div class="form-group col-12">
        <label>Date de début</label>
        <%= f.text_field :start_date, class: "form-control"%>
      </div>
      <div class="form-group col-12">
        <label>Durée</label>
        <%= f.text_field :duration, class: "form-control"%>
      </div>
      <div class="form-group col-12">
        <label>Localisation</label>
        <%= f.text_field :location, class: "form-control"%>
      </div>
      <div class="form-group col-12">
        <label>Prix</label>
        <%= f.text_field :price, class: "form-control"%>
      </div>
      <div class="form-group text-right col-12">
        <button type="submit" class="btn btn-warning">Modifier cet évent</button>
      </div>

      <% end %>
    </div>

<div class="row justify-content-center">
  <h3>Changer la photo de l'événement ?</h3>
  <%= form_tag event_event_pictures_path(@event), multipart: true do %>
    <%= file_field_tag :event_pictures %>
    <%= submit_tag "Mettre à jour" %>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="jumbotron">
  <div class="container">
	<% unless current_user %>
	  <h1>Bienvenue !</h1>
	<% else %>
	  <h1 class="display-3">Bienvenue <%= current_user.first_name %> !</h1>
	<% end %>      
    <p>Eventbrite rapproche les gens grâce à des expériences en direct. Découvrez des événements qui correspondent à vos passions ou créez votre propre événement...</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
  </div>
</div>


<div class="container">
    <h2>Nos événements</h2>

    <div class="row">
      <% i = 0
	  @events.each do |event| %>
	  <div class="col-lg-4 mb-4 md-4 t-4">
	  	<div class="card h-100 text-center">
	  	  <%if @events[i].event_picture.attached?%>
	  	    <%= image_tag @events[i].event_picture, alt: 'event_picture' %>
	  	  <%else%>
  		    <p>=== Il n'y a pas encore de photo lié à cet événement ===</p>
	  	  <%end%>
	  	  
	  	  <div class="card-body">
	  	    <h4 class="card-title"><%=@events[i].title%></h4>
	  	    <h6 class="card-subtitle mb-2 text-muted">Le <%=@events[i].start_date%>, à <%=@events[i].location%>, pendant <%=@events[i].duration%> heure(s)</h6>
	        <p class="card-text"><%=@events[i].description%></p>
	      </div>
	    
	      <div class="card-footer">
            <a class="btn btn-secondary" href="<%= event_path(@events[i].id)%>" role="button">View details »</a>
          </div>
	      
	    </div>
	    <% i += 1 
	    end %>
	  </div>
	</div>
</div>


      

app/views/events/new.html.erb
<div class="row justify-content-center">
    <%= form_for @event do |f| %>
      <div class="form-group col-12">
        <label>Titre de l'événement</label>
        <%= f.text_field :title, class: "form-control"%>
      </div>
      <div class="form-group col-12">
        <label>Description</label>
        <%= f.text_field :description, class: "form-control"%>
      </div>
      <div class="form-group col-12">
        <label>Date de début</label>
        <%= f.text_field :start_date, class: "form-control"%>
      </div>
      <div class="form-group col-12">
        <label>Durée</label>
        <%= f.text_field :duration, class: "form-control"%>
      </div>
      <div class="form-group col-12">
        <label>Localisation</label>
        <%= f.text_field :location, class: "form-control"%>
      </div>
      <div class="form-group col-12">
        <label>Prix</label>
        <%= f.text_field :price, class: "form-control"%>
      </div>
      <div class="form-group text-right col-12">
        <button type="submit" class="btn btn-warning">Créer cet évent</button>
      </div>

      <% end %>
    </div>

app/views/events/show.html.erb
<div class="jumbotron">
  <div class="container">
	<h1 class="display-3 text-center"><%=@event.title%> en détail !</h1>     
  </div>
</div>

<div class="container text-center">
  <div class="col t-4 text-center">
  	<%if @event.event_picture.attached?%>
	  	<%= image_tag @event.event_picture, alt: 'event_picture' %>
	  <%else%>
  		<p>=== Il n'y a pas encore de photo lié à cet événement ===</p>
	  <%end%>
	<p><em><%=@event.description%></em></p>
	<p>Le <%=@event.start_date%></p>
	<p>A <%=@event.location%></p>
	<p>Pendant <%=@event.duration%> heure(s)</p>
	<p>Pour <%=@event.price%> €</p>
	<p>Créé par <%=User.find(@event.administrator_id).email%></p>
	<p>Participants : <%=@attendants%></p>

	<h3>Changer de photo ?</h3>
	<%= form_tag event_event_pictures_path(@event), multipart: true do %>
  	  <%= file_field_tag :event_picture %>
  	  <%= submit_tag "Mettre à jour" %>
	<% end %>


	<% unless @administrator.id == current_user.id %>
		<p><a class="btn btn-secondary" href="<%=new_event_attendance_path(@event.id)%>" role="button">Prendre sa place »</a></p>
	<% else %> 
		<p><a class="btn btn-secondary" href="<%=event_attendances_path(@event.id)%>" role="button">Mon espace événement</a></p>
	<% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  </head>

   <body>
    <nav class="navbar navbar-expand-lg d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 navbar-dark bg-dark">
      <a class="navbar-brand font-weight-normal">Eventbrite</a>
      <div class="collapse navbar-collapse my-2 my-md-0 mr-md-3" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" href="<%= home_path %>">Home<span class="sr-only">(current)</span></a>
          <a class="nav-link" href="<%= new_event_path%>">Créer un événement</a>
        </div>
      </div>

      <% unless user_signed_in? %> 
        <div class="dropdown dropleft">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Se connecter/ S'inscrire</a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a>
            <a class="dropdown-item" href="<%= new_user_registration_path %>">S'inscrire</a>
          </div>
        </div>
      
      <% else %>
        <div class="dropdown dropleft">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mon profil</a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="<%= user_path(current_user) %>">Mon profil</a>
            <a href="<%= destroy_user_session_path %>" class="dropdown-item" data-confirm="Etes-vous sûr de votre choix?" data-method="DELETE">Se déconnecter</a>
          </div>
        </div>
      <% end %>
    </nav>

    <%= yield %>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
      <div class="row justify-content-center">
        <div class="col-1"><a class="nav-link" href="<%= home_path %>">Home</a></div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="jumbotron">
  <div class="container">
	<h1 class="display-3">Votre profil Eventbrite</h1>    
    <p><%= current_user.first_name %></p>
    <p><%= current_user.last_name %></p>
    <p><%= current_user.description %></p>
    <p><%= current_user.email %></p>
    <p><a class="btn btn-primary btn-lg" href="<%= edit_user_registration_path %>" role="button">Modifier mon email ou mon mot de passe »</a></p>
  </div>
</div>

<div class="container text-center">
  <div class="row">
	<% i = 0
	@events_admin.each do |event| %>
	<div class="col-md-4 t-4 text-center">
	  <h2><%=Event.find(@events_admin[i].id).title%></h2>
	  <p>Le <%=Event.find(@events_admin[i].id).description%></p>
	  <p><a class="btn btn-secondary" href="<%= event_path(@events_admin[i].id)%>" role="button">View details »</a></p>
	</div>
	<% i += 1 
	end %>

  </div>
</div>